# Generated by Django 5.1.6 on 2025-03-02 15:52
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_parrots', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(primary_key=True, max_length=255, auto_created=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('car_parrot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parrots.carparrot')),
            ],
        ),
    ]
