# Generated by Django 5.1.6 on 2025-04-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_parrots", "0003_delete_carparrot"),
        ("vehicles", "0002_alter_vehicle_car_parrot_id_alter_vehicle_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="car_parrot_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="car_parrots.carparrots",
            ),
        ),
    ]
