# Generated by Django 5.2 on 2025-04-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation_status', '0003_alter_violationstatus_id'),
        ('violation_status', '0004_add_ai_reliable_status'),
    ]

    operations = [
    ]
