# Generated by Django 5.1.6 on 2025-03-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.CharField(max_length=255)),
                ('output_url', models.CharField(max_length=255)),
            ],
        ),
    ]
