# Generated by Django 5.1.6 on 2025-03-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('violation_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('tracking_id', models.CharField(max_length=255, null=True, blank=True)),  # Optional
                ('max_confidence', models.FloatField(null=True, blank=True)),
                ('violation_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation_status.violationstatus')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
