# Generated by Django 5.1.6 on 2025-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violation",
            name="detected_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="violation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
