# Generated by Django 5.1.6 on 2025-04-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0002_alter_camera_id_alter_camera_status"),
        ("violations", "0002_alter_violation_detected_at_alter_violation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violation",
            name="camera_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cameras.camera",
            ),
        ),
    ]
