# Generated by Django 5.1.6 on 2025-03-02 15:52

import django.db.models.deletion
from django.db import migrations, models
from django.forms import CharField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('to_email', models.CharField(max_length=255)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification'))
            ],
        ),
    ]
