# Generated by Django 5.1.6 on 2025-04-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
        ("violations", "0002_alter_violation_detected_at_alter_violation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mail",
            name="notification_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="violations.violation"
            ),
        ),
    ]
