# Generated by Django 5.2 on 2025-04-24 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_alter_mail_id_alter_mail_notification_id'),
        ('notifications', '0002_alter_notification_id_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='notification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification'),
        ),
    ]
