# Generated by Django 5.1.6 on 2025-03-02 15:52
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='CarParrot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('status', models.CharField(
                    max_length=9, 
                    choices=[('Submitted', 'Submitted'), ('Verified', 'Verified')],
                    default='Submitted', 
                    verbose_name='Status of registration: [Submitted, Verified]'
                    )),
                ('plate_number', models.CharField(max_length=255)),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.citizen')),
            ],
        ),
    ]
