# Generated by Django 5.1.6 on 2025-04-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_parrots", "0001_initial"),
        ("citizens", "0002_alter_citizen_address_alter_citizen_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carparrot",
            name="citizen_id",
        ),
        migrations.CreateModel(
            name="CarParrots",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.TextField()),
                ("status", models.CharField(max_length=255)),
                ("plate_number", models.CharField(max_length=255)),
                (
                    "citizen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citizens.citizen",
                    ),
                ),
            ],
        ),
    ]
