# Generated by Django 5.1.6 on 2025-04-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_parrots", "0002_remove_carparrot_citizen_id_carparrots"),
        ("vehicles", "0002_alter_vehicle_car_parrot_id_alter_vehicle_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarParrot",
        ),
    ]
