# Generated by Django 5.2 on 2025-04-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_parrots', '0002_carparrots_owner_address_modelcode_color'),
        ('car_parrots', '0003_delete_carparrot'),
    ]

    operations = [
    ]
