# Generated by Django 5.2 on 2025-04-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_parrots', '0004_merge_20250422_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparrots',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carparrots',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carparrots',
            name='modelCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carparrots',
            name='owner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carparrots',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Verified', 'Verified')], default='Submitted', max_length=9, verbose_name='Status of registration: [Submitted, Verified]'),
        ),
    ]
