# Generated by Django 5.1.6 on 2025-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('last_active', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
