# Generated by Django 5.1.6 on 2025-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="camera",
            name="status",
            field=models.CharField(max_length=255),
        ),
    ]
