# Generated by Django 5.1.6 on 2025-03-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    max_length=8, 
                    choices=[('Sent', 'Sent'), ('Replied', 'Replied')],
                    default='Sent', 
                    verbose_name='Status of account: [Sent, Replied]'
                    )),
                ('created_at', models.DateTimeField()),
                ('violation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.violation'))
            ],
        ),
    ]