# Generated by Django 5.1.6 on 2025-04-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violation_images", "0002_alter_violationimages_id"),
        ("violations", "0003_alter_violation_camera_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationimages",
            name="violation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="violations.violation",
            ),
        ),
    ]
