"""
Django settings for HVDS_BE project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-tz#f_j0o%7ze@6ni-iek-q0ei56fd7p60vgf#ky=kr6*p_-%49"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
APPEND_SLASH=False

# Application definition

INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        'rest_framework',
        'rest_framework_simplejwt',
        'rest_framework_simplejwt.token_blacklist',
        'django_filters',
        'corsheaders',
        'accounts',
        'camera_urls',
        'citizens',
        'cameras',
        'violations',
        'vehicles',
        'notifications',
        'locations',
        'mails',
        'violation_images',
        'violation_status',
        'car_parrots'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

# CORS_ALLOWED_ORIGINS = [
#     "https://localhost:5173",
#     "http://localhost:3000",
# ]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://localhost:5173",
    "http://localhost:3000",
]
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = "HVDS_BE.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HVDS_BE.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        'TEST': {
            'NAME': BASE_DIR / "db_test.sqlite3"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTH_USER_MODEL = "accounts.Account"
# Code thêm ở đây
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # Session timeout 30 phút
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }

# Backend lưu session (mặc định là database, hoặc dùng cache/memory cho đơn giản)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Hoặc 'cache' nếu muốn nhanh hơn
SESSION_COOKIE_AGE = 300  # Timeout mặc định cho session (1200 giây = 20 phút)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# settings.py
TWILIO_ACCOUNT_SID = 'AC85189322cd8bf5c6150409cc5332730e'
TWILIO_AUTH_TOKEN = '827b95cb1b6b1f0b921e0ba36d63dcf0'
TWILIO_PHONE_NUMBER = '+19787338553'
COUNTRY_CODE = '+84'  # Vietnam country code

# EMAIL
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'hanaxuan1study@gmail.com'
EMAIL_HOST_PASSWORD = 'llqw hvug zlfe tpfu'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
CSRF_COOKIE_SECURE = False

# SpeedSMS Configuration
SPEEDSMS_ACCESS_TOKEN = os.getenv('SPEEDSMS_ACCESS_TOKEN', '_T_eE0L21YIYEtif0627Pp_8-D0MyHo-')
SPEEDSMS_API_URL = 'https://api.speedsms.vn/index.php/sms/send'

# Stringee API credentials (replace with your own)
STRINGEE_KEY_SID = "SK.0.sFAW2g7DEWTmZ04oZbQvc4ktrdMI2U" 
STRINGEE_KEY_SECRET = "RGc0WjFHZ3FCYW02VDZGSW5BMWV2SGN4WWF2SEdEUA==" 
STRINGEE_FROM_NUMBER = "842871029693"  # Stringee-provided number (e.g., "+842412345678")
STRINGEE_URL = "https://api.stringee.com/v1/call2/callout"
FILE_DATA_PATH = f'{BASE_DIR} + /data.xlsx'
LOGIN_URL = "http://localhost:7860/api/accounts/login/"
CREATE_CAMERA_url = "http://localhost:7860/api/cameras/create/"
AI_SERVICE_URL = 'https://huyhoanlee-ai-service.hf.space'