# Generated by Django 5.1.6 on 2025-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_identity_id', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('identity_card', models.TextField()),
                ('status', models.CharField(
                    max_length=9, 
                    choices=[('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Created', 'Created')],
                    default='Created', 
                    verbose_name='Status of registration: [Submitted, Verified, Created]'
                    )),
                ('otp', models.CharField(max_length=6, null=True, blank=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True)),
                ('dob', models.DateField(null=True, blank=True)),
                ('place_of_birth', models.CharField(max_length=255, null=True, blank=True)),
                ('gender', models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True, blank=True)),
                ('issue_date', models.DateField(null=True, blank=True)),
                ('place_of_issue', models.CharField(max_length=255, null=True, blank=True)),
                ('nationality', models.CharField(max_length=100)),
                ('person_image', models.TextField()),
            ],
        ),
    ]
