# Generated by Django 5.1.6 on 2025-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="status",
            field=models.CharField(max_length=255),
        ),
    ]
