# Generated by Django 5.2 on 2025-04-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_alter_citizen_address_alter_citizen_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='expires_at_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='otp_email',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
